- name: fetch logstash
  get_url: url={{ logstash_url }}-{{ logstash_version }}.tar.gz dest=/tmp/logstash-{{ logstash_version }}.tar.gz

- name: install logstash
  register: logstash_untar
  command: tar -xzf /tmp/logstash-{{ logstash_version }}.tar.gz -C /home/vagrant
  
- name: upload logstash configs
  copy: src=logstash.conf dest=/home/vagrant/logstash.conf
